### ISSUE TITLE
[2장] 실수형이 정수형보다 훨씬 큰 값을 표한할 수 있으나 오차가 발생할 수 있는 이유 

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#1]
p.30
실수형과 정수형이 같은 크기이더라도 실수형은 정수형과 저장 형식이 달라 훨씬 큰 값을 표현 할 수 있다고 합니다. 
어떻게 저장방식이 다르기에 실수형이 더 많은 값을 표현 할 수 있는지 궁금합니다. 

또한, 실수형은 오차가 발생할 수 있다고 합니다. 
실수형에서 오차가 발생하는 이유가 무엇인지 궁금합니다. 

1. 실수형이 정수형보다 많은 값을 표현할 수 있는 이유
2. 실수형에서 오차가 발생하는 이유 

> 후반부에 해결된 질문

**Comment by yujeongkimm** [comment]
1. int형과 float 타입 모두 4Byte씩 저장할 수 있지만, 실수형이 더 큰 값을 표현할 수 있습니다.
그 이유는 바로 값을 저장하는 형식이 다르기 때문입니다.

책 p.69의 그림 2-13은 int 타입과 float타입의 표현방식을 비교한 것인데, int 타입은 '부호와 값', 두 부분으로 이루어져있지만, float 타입과 같은 실수형은 '부호(S), 지수(E), 가수(M)', 세 부분으로 이루어져 있습니다. 즉 2의 제곱을 곱한 형태(±M x 2^E)로 저장하기 대문에 큰 범위의 값을 저장할 수 있습니다.


2. IEEE-754 부동소수점 표준에 의해 소수가 2진으로 저장되기 때문이다. 1/7(0.142857142857... ), 0.1과 같은 소수들은 2진수로 표현할 방법이 없습니다. 컴퓨터는 그 값과 가장 근사한 값을 반환하는 것이고, 이때 부동소수점의 부정확성이 나타납니다. 

IEEE-754란? 컴퓨터에서 부동소수점을 표현하는 가장 널리 쓰이는 표준

**Comment by Park-EunBi** [comment]
> 추가 질문 (스터디 중 생긴 의문)       

p.69
가장 앞 비트를 부호 비트로 사용한다고 했을 때 

32bit의 int형 변수로 표현할 수 있는 정수의 개수는 2^31 개 이며, 
32bit의 float 변수로 표현할 수 있는 정수(지수 부분)의 개수는 2^8개 입니다. 
(n비트로 표현할 수 있는 정수의 개수: 2^n개)

표현할 수 있는 정수의 개수로 본다면 int 형 변수가 float 변수보다 많은 개수의 정수를 표현할 수 있는데 
실수형이 정수형보다 많은 값을 표현할 수 있다는 게 무슨 의미인지 궁금합니다.

**Comment by yujeongkimm** [comment]
_'즉 2의 제곱을 곱한 형태(±M x **2^E**)로 저장하기 때문에 큰 범위의 값을 저장할 수 있습니다.'_ 에서
E는 지수를 저장하는 부분으로 float의 경우, 8bit의 저장공간을 갖습니다. 지수는 부호있는 정수이고 8bit는 모두 2^8(=256)개의 값을 저장할 수 있으므로, -127 ~ 128의 값이 저장됩니다. 이 중 '숫자 아님(NaN)'이나 '양의 무한대', '음의 무한대'를 빼고 실제로 사용가능한 지수의 범위는 -126 ~ 127입니다.

지수의 최대값이 127이므로 float 타입으로 표현할 수 있는 최대값은 2^127이고, 
10진수로 약 10^38입니다.

따라서 int 타입으로 표현 가능한 최대 값인 (2^31)-1 보다 더 많은 값을 표현할 수 있습니다.
