### ISSUE TITLE
[5장] 길이가 0인 배열을 생성하는 이유 

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#10]
p. 188
자바에서는 배열의 길이가 0인 배열을 생성할 수 있다고 합니다.
배열의 길이가 0이라는 것은 
"배열에 값을 저장할 수 없다" 라고 할 수 있는데 해당 배열을 생성하는 이유가 궁금합니다. 

1. 길이가 0인 배열을 생성하는 것의 의미
2. 해당 배열이 필요한 상황 (언제 유용한지)

**Comment by allzeroyou** [comment]
책을 읽다보면, 확 와닿진 않지만 다음 기회를 노리며 어물쩍 넘어갈 때가 있습니다.
남겨주신 이슈 역시, 저도 왜 그런건지 궁금했지만 넘어간 내용입니다.
이를 명쾌하게 찝어서, 이슈를 남겨주셔서 감사합니다.

------------------
# 1. 길이가 0인 배열을 생성하는 것의 의미

자바에서는 배열의 길이가 0인 배열을 생성할 수 있습니다.
배열의 길이는 배열의 요소의 개수, 즉 값을 저장할 수 있는 공간의 개수입니다.
즉, 길이가 0이라는 건은 값을 저장할 수 있는 공간이 없다는 의미입니다.

# 2. 해당 배열이 필요한 상황 (언제 유용한지)

이때 null과 0(empty)는 구분해야 합니다.
empty: 길이가 0인 배열(zero-length array), 즉 비었다라는 뜻입니다.
null: 변수에 아무것도 할당되지 않은 상태(no value at all)를 의미합니다.


자바에서 흔히 마주칠 수 있는 에러는 NullPointerException입니다. 
이를 방지하기 위해 `if(object != null)` 등의 null을 체크하는 코드를 추가합니다.
이때, 길이가 0인 배열을 사용한다면, 에러를 방지하며, null을 체크하는 코드를 넣을 필요도 없어집니다. 

자료를 찾아보다가 이러한 원리를 이용한 기법인 `널 오브젝트 패턴` 이라는 디자인 패턴이 있다는 걸 발견해 첨부합니다.


참고
https://bb-library.tistory.com/207
https://johngrib.github.io/wiki/pattern/null-object/
https://kunoo.tistory.com/entry/%ED%96%89%EC%9C%84-%ED%8C%A8%ED%84%B4-Null-Object-pattern-%EB%84%90-%EC%98%A4%EB%B8%8C%EC%A0%9D%ED%8A%B8-%ED%8C%A8%ED%84%B4
