### ISSUE TITLE
[6장] 클래스 변수와 static 키워드

### ISSUE THREAD

**Issue by allzeroyou** [yujeongkimm/ReadingRecord#12]
p.246
클래스 변수를 선언하는 방법은 인스턴스 변수 앞에 static을 붙이기만 하면 되고, 독립적인 저장공간을 갖는 인스턴스변수와는 달리, 클래스 변수는 모든 인스턴스가 공통된 저장공간을 공유한다고 합니다.

이때, static키워드는 public static void main(String args[])에도 들어가는데요, 이처럼 자바에서 자주 쓰이는 'static' 키워드의 의미를 알고 싶습니다.

1. static 키워드 의미(public, private과 같은 접근제어자과는 다른 성격인가요?)
2. 어떨 때 사용하는지

**Comment by yujeongkimm** [comment]
1. 
static은 메모리 효율 관점에서 사용하는 키워드로 접근 제어자와는 다른 성격으로 쓰입니다. 
static 메모리 영역은 고정된 메모리 영역을 사용하기 때문에 매번 인스턴스를 생성하며 낭비되는 메모리를 줄여 메모리 측면에서 효과적입니다. 
하지만 무분멸하게 이 곳에 저장하면 메모리 낭비가 발생하여 필요한 변수만 사용할 필요가 있습니다.

2.
정적(static)멤버 선언을 예로 들어보겠습니다. 
필드나 메소드를 생성 시 인스턴스로 생성할 것인지 정적으로 생성할 것인지에 대한 판단 기준은 공용으로 사용하느냐 아니냐로 내리면 됩니다. 
그냥 생성한다면 자동으로 인스턴스가 생성되고, 정적으로 생성하려면 필드와 메소드 선언 시 static 키워드를 추가적으로 붙입니다.

3. 추가적으로 static에 대한 개념,

Q. 왜 main()메서드에는 static으로 선언되었을까?
A. 질문 주신 내용과 같이 자바의 main메서드는 static으로 선언되었습니다. java프로그램이 실행하기 전에 static 변수, 메소드를 첫 단게에 메모리에 올려 프로그램을 실행시킵니다. (static이 1순위로 실행됩니다.)
즉, 자바가상머신 JVM에서 객체를 생성하지 않고도 메모리에 호출시켜 할당이 가능합니다. 
main함수가 실행되기 위해서는 메모리에 미리 올라가 있어야합니다. 그렇지 않다면 처음에 main이 없어 실행이 불가능합니다. 

static이 아닌 경우를 생각해보겠습니다.
```java
메인 클래스 변수 = new 메인클래스();
변수.main();
```
객체가 생성되는 런타임(Runtime)시에 메모리에 할당되므로, 객체가 new 키워드를 이용하여 생성이 되야 객체 메모리에 할당되어 접근 및 호출이 가능합니다. 
즉, main함수가 실행되기 위해서는 객체가 메모리에 미리 올라가 있어야 합니다. 

결론으로 main 메소드는 인스턴스 생성과 관계없이 JVM에 의해 호출되므로 반드시 static으로 선언 되어야합니다. 


Q. 자바에서 static 사용을 지양하는 이유는?
A. 객체지향 측면에서 생각해 볼 수 있습니다. 먼저 static은 객체 지향적이지 않습니다. 객체지향 프로그래밍 원칙에 따르면, 한 객체가 지니고 있는 데이터들은 외부에서 함부로 접근하여 수정할 수 없도록 해야합니다. 따라서 static 변수는 각 객체의 데이터들이 캡슐화되어야 한다는 객체지향 프로그래밍 원칙에 위반됩니다.
두번째로 static 변수는 프로그램이 실행되는 동안 계속 살아있다는 점입니다. JVM의 static 영역은 프로그램이 종료할 때까지 메모리에 남아있습니다. 결국, static 변수는 프로그램이 실행되고 있는 동안 계속 살아있게 되므로 함수 내에서 인스턴스를 생성하는 것이 함수 호출이 끝난 후 인스턴스가 소멸되어 객체의 라이프타임에 더욱 적합합니다.
~~마지막으로 static은 재사용성이 떨어집니다. static 메서드는 인터페이스를 구현하는데 사용될 수 없어 재사용성을 높여주는 객체지향적 설계에 방해될 수 있습니다.~~ -> 자바 8버전 이후부터 인터페이스에 기본 메소드(default method)와 스태틱 메소드(static method)를 사용할 수 있음!



참고:
https://unabated.tistory.com/1041

**Comment by Park-EunBi** [comment]
자세한 설명 감사합니다. 
추가 질문에 대한 상세한 설명을 넘어 추가적인 개념까지 설명해주셔서 static 에 대해 좀 더 많은 내용을 이해할 수 있게 되었습니다. 

유정님께서 작성해주신 static에 대한 설명에서 추가적으로 궁금한 점이 생겨 해당 내용에 대한 답변을 달게 되었습니다. 

static은 프로그램이 종료 되기 전 까지 메모리에 살아있기에 객체 지향적이지 않다고 말씀해주셨습니다. 
그렇다면 `static 변수는 절대 중간에 반환될 수 없는 것인지`에 대한 궁금증이 생겨 해당 내용에 대해 찾아보게 되었습니다. 

[static 변수의 메모리 해제]

**1. static 변수에 null 값을 넣어주기** 
static 변수가 참조하고 있는 값을 null로 변경하게 되면 해당 변수가 참조하는 참조 객체가 사라진다. 
이후 java의 Garbage Collection가 해당 메모리를 수거하게 되어 static 변수의 메모리가 해제된다. 

**2. Garbage Collection를 사용하여 메모리 참조를 제거하기** 
JDK 1.2 이후부터는 java.lang.ref 를 통해 제한적으로 Garbage Collection를 사용할 수 있게 되었다. 
해당 클래스의 메소드를 사용하면 static 변수의 값을 해제할 수 있다 
(자세한 내용은 참조 링크를 참고해주세요)


참고 
https://swlock.blogspot.com/2014/11/java_15.html
https://hpotter1993.tistory.com/26
