### ISSUE TITLE
[6장] static 메서드의 인스턴스 메서드 호출 

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#14]
p. 255 (메서드의 실행흐름)

같은 클래스 내의 메서드끼리는 참조변수를 사용하지 않고도 서로 호출이 가능한 반면에 
static 메서드는 같은 클래스 내의 인스턴스 메서드를 호출 할 수 없다고 합니다. 

static 메서드는 같은 클래스 내의 인스턴스 메서드를 호출 할 수 없다는 것의 의미가 잘 이해가 되지 않습니다. 

해당 내용을 예시를 들어 설명해주실 수 있으실까요?

**Comment by yujeongkimm** [comment]
인스턴스 메서드에서 static이 붙은 변수 및 메서드를 사용하는 것은 언제든 가능하지만, static 메서드에서 인스턴스 메서드의 사용을 금지합니다.
static 메서드는 인스턴스를 생성하지 않아도 호출이 가능하여 static 메서드가 호출되었을 때 인스턴스가 존재하지 않을 수 있기 때문입니다.

```java
class TestClass{
	void instanceMethod() {}	// 인스턴스메서드
    	static void staticMethod() {} // static메서드
    
    	void instanceMethod2() { // 인스턴스메서드
    		instanceMethod(); // 다른 인스턴스메서드를 호출
        	staticMethod(); // static메서드를 호출
    	}
    
    	static void staticMethod2() { // static메서드
    		instanceMethod();	// 에러! 인스턴스메서드를 호출할 수 없다.
        	staticMethod();		// static메서드는 호출
    	}
} 
```
