### ISSUE TITLE
[6장] 재귀호출

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#15]
p.270

대부분의 재귀 호출은 반복문으로 작성 가능합니다.  
그러나 재귀 호출은 
매개변수 복사와 종료 후 복귀할 주소 저장 등이 추가로 필요하여 반복문보다 수행 시간이 더 오래 걸립니다. 

교재에 제시된 항목(매개변수 복사와 종료 후 복귀할 주소 저장) 말고도 재귀 호출에서 수행 시간을 증가 시키는 요인이 무엇인지 궁금합니다. 
또한,  반복문으로 작성 가능한 코드를 재귀 호출로 작성하였을 때 어떤 이점이 있는지 궁금합니다. (수행 시간 증가라는 단점에도 재귀호출 코드를 작성하는 이유)

1. 재귀 호출에서 수행 시간을 증가시키는 요인
2. 재귀 호출을 사용의 이점

> 후반부에 해결된 질문

**Comment by yujeongkimm** [comment]
1. 함수 호출을 많이 하기에 StackOverFlow Error가 일어날 가능성이 있습니다. 
교재 p.271의 FactorialTest.java에서 만약 factorial메서드의 매개변수 n의 값이 0이 되면, if문의 조건식이 절대 참이 될 수 없기 대문에 계속해서 재귀호출만 일어날 뿐 메서드가 종료되지 않아 스택에 계속 데이터가 쌓입니다. 어느 시점에 이러서는 스택의 저장한계를 넘고 StackOverFlow 에러가 발생합니다. 

2. 몇 겹의 반복문과 조건믄으로 복합하게 작성한 코드가 재귀호출로 작성하면 보다 단순한 구조로 바뀔 수 있습니다. 아무리 효율적이라도 알아보기 힘들게 작성하는 것보다 다소 비효율적이라도 알아보기 쉽게 작성하는 것이 논리적 오류가 발생할 확률도 줄어들고 나중에 수정하기도 좋습니다. 
재귀호출에 드는 비용보다 재귀호출의 간결함이 주는 이득이 충분히 큰 경우에만 사용해야 합니다.

**Comment by allzeroyou** [comment]
> "반복문은 그저 같은 문장을 반복해서 수행하는 것이지만, 메서드를 호출하는 것은 반복문보다 몇가지 과정, 예를 들면 매개변수 복사와 종료 후 복귀할 주소 저장 등, 이 추가로 필요하기 때문에 반복문보다 재귀호출의 수행시간이 오래 걸린다." 

평소 재귀함수는 시간복잡도가 크기 때문에, 조건 제한이 있는 코딩테스트같은 경우 "재귀함수보다는 반복문을 사용해야 통과할 수 있다." 라는 결과론적인 정보를 가지고 있었습니다. 이따금 '왜 그런거지?' 라는 궁금증이 들곤 했는데, 솔직히 귀찮아서 넘어갔었어요.
은비님께서 좋은 질문 해주셔서 덕분에 저도 시간을 내어 차분히 찾아볼 수 있었습니다.

감사합니다.
아래는 제가 찾은 정보입니다. 

-----------------

1. 교재에서 제시된 항목외의 재귀호출에서 수행시간을 증가시키는 요인
- 재귀함수는 단순한 구조인 반복문보다는 아무래도 수행할 꺼리(?)가 많은 메서드 라는 점입니다.

좀더 고급 용어를 사용해서 설명하면,

재귀함수의 가장 대표적인 사용 예제는 `팩토리얼`입니다.

```java
int factorial(int n) { 
    if (n === 1) { 
        return 1; 
    } 
    return n * factorial(n-1);
}
```
가령 예를 들어 인자로 5를 넘긴다면..
이해하기 쉽게 해당 코드가 수행될 때의 콜스택을 살펴보면,
![image](https://user-images.githubusercontent.com/71822139/216772964-009080f8-5acc-4eb9-b90d-a2d5bf85cfa3.png)
함수를 호출할 때마다 콜스택에는 함수의 **매개변수, 지역변수, 반환주소** 값 등을 모두 저장하게 됩니다.
**factorial(5)** 호출 → 반환타입 부분에서의 **5 * factorial(5-1)** 수행 → **factorial(4)** 호출 → **반환 waiting...**

그럼 그 다음에는 어떤 일이 일어날까요?

동일하게 **factorial(4)**에 대한 **매개변수, 지역변수, 반환주소** 값이 콜스택에 쌓이게 됩니다. 이렇게 팩토리얼5부터 팩토리얼1까지 차곡차곡 콜스택이 쌓이게 되고, factorial(1)에서 if(n==1)라는 분기에 걸리면서 드!디!어! 해당 콜스택이 하나씩 수행되며 사라집니다.

하지만 반복문으로 팩토리얼을 작성하게되면...
```java
int factorial(int n) { 
    int result = 1;
    while (n != 0) { 
        result *= n--;
    return result;
}
```
![image](https://user-images.githubusercontent.com/71822139/216773264-c9709cf1-f106-4de3-b10f-ce401c646ef9.png)
위의 그림과 같이, (보기에도 단순해보이는..)
**지역변수, 매개변수, 반환값**을 모두 스택에 저장해야 하는 재귀함수와 달리 반복문은 많은 수의 반복에도  **스택오버플로우**와 같은 메모리 부족 문제를 겪지 않으며, 속도도 빠릅니다.

2. 2번은 위의 유정님께서 남겨주신 답변의 내용과 동일하게 생각합니다.

다만, 그렇다면 이러한 재귀함수의 문제를 _온전히 재귀함수를 사용하면서 나아질 수는 없는건가_라는 궁금증이 들었습니다.
있더군요. 재귀함수의 단점을 해결할 수 있는 법.

바로, **꼬리 재귀** 입니다.


재귀함수의 가장 큰 문제가 자기 자신을 호출 한 후  마냥 결과를 기다리면서 생기는 **콜스택의 부하로 인한 메모리 낭비**였습니다.
이때 `꼬리 재귀` 라는 개념을 이용한다면, _재귀호출이 끝나는 시점에서 아무일도 하지 않고 바로 결과를 반환하도록 하는 방법_으로 함수의 상태 유지 및 추가 연산을 하지 않아도 되기에, 스택오버플로우를 해결 할 수 있다고 합니다.

```java
// Basic Recursion
int factorial(int n, int total) { 
    if (n === 1) { 
        return 1; 
    } 
    return n * factorial(n-1);
}

// Tail Recursion
int factorial(int n, total) {
    if (n === 1) { 
        return 1; 
    } 
    return factorial(n - 1, n * total);
}
```
기존 재귀함수와 차이점을 보면..
**반환부분** 코드가 달라졌는데요, 꼬리 재귀의 핵심은 반환부에 연산이 없어야 한다는 점입니다.
이렇게 **반환부에 연산이 없도록** 구현 한다면, 컴파일러는 `꼬리 재귀 최적화` 를 지원해 자체적으로 _재귀함수 해석 → 반복문으로 변경_해서 실행한다고 합니다.(우와)

[참고한 링크](https://catsbi.oopy.io/dbcc8c79-4600-4655-b2e2-b76eb7309e60)

**Comment by Park-EunBi** [comment]
와우 두 분의 자세한 설명 덕분에 궁금한 점이 해결 되었습니다. 
감사합니다. 

다영님께서 언급해주신 꼬리재귀에 대해 조금 보탬이 되고자 꼬리 재귀에 대한 아래 링크를 첨부합니다. 
https://github.com/Park-EunBi/TIL/blob/main/Algorithm/Tail-recursive.md
말씀해주신 내용과 거의 동일한 내용 같기는 하지만... 공유해봅니다!
