### ISSUE TITLE
[6장] 가변인자 구별

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#18]
p.287

가변인자는 가변인자인지 아닌지를 구별할 방법이 없기에 
항상 매개변수의 마지막에 선언해야 한다고 합니다. 

가변인자를 구별할 수 없는데 가변인자임을 판단하여 동적으로 매개변수를 할당할 수 있다는 것이 이해가 잘 가지 않습니다. 

해당 내용을 가변인자 동작 매커니즘을 통해 설명해주실 수 있으실까요?

**Comment by allzeroyou** [comment]
가변인자는 가변인자인지 아닌지 구별할 수 없기 때문에 항상 매개변수의 마지막에 선언해야 합니다.

이때, _가변인자가 맞는지 아닌지 구별할 수 없는데 동적으로 매개변수를 할당할 수 있다는 것이 이해가 잘 가지 않는다고_ 하셨습니다.

저는 질문의 인과관계(?)가 살짝 반대로 된 것 같다는 생각이 들었습니다.

당연히, **가변인자가 맞는지 아닌지 불분명한 상태**에서는 **동적으로 매개변수를 할당할 수 없는게 맞습니다.**

예를 들어,
```java
public class VarargsTest {
    public static void main(String[] args) {
        printNumbers(1, 2, 3);
    }

    public static void printNumbers(int... numbers,int x) {
        System.out.println(x);
        for (int number : numbers) {
            System.out.println(number);
        }
    }
}
```
위의 코드는 컴파일 에러가 나는데요, 오류 메시지는 `java: varargs parameter must be the last parameter` 이며 가변인수는 **반드시 마지막 파라미터에 위치해야 된다**는 내용입니다.
이처럼 마지막 파라미터에 없다면, 즉 **가변인자가 맞는지 아닌지 불분명할 때는 동적으로 매개변수를 할당할 수 없습니다.** 가변인수를 사용할 수 없는거죠.

왜냐면, 위의 코드를 보면 2,3중 어디까지가 가변인자로 전달되면 좋을지 컴파일러는 알리가 만무합니다. 따라서 _가변인자를 파라미터의 맨 끝으로 배치해_, 앞 순서까지의 매개변수를 전달한 후, **남은건 모두 가변인자로 처리**한다고 생각합니다.

----------

가변인자의 동작 매커니즘은..

가변인자로 처리될때는 가변인자가 **배열**로 메서드에 전달됩니다.

예를 들어,
```java
public class VarargsTest {
    public static void main(String[] args) {
        myMethod("first", "second", "third", "fourth", "fifth");
    }
    public static void myMethod(String... strings)   {
        for (String s: strings)    {
            // Applying some logic / treatment on strings
            System.out.println(s);
        }
    }
}
```
위와 같은 코드에서는, `strings` 파라미터는 배열로서 `String[]`로 내부적으로 처리됩니다. 매개변수의 순서는 메서드에 전달되어 문자열 배열에 저장될 때 유지됩니다. `strings` 배열은 다음과 같은 요소들을 포함하고 있는거죠.
```java
strings[0] = "first"
strings[1] = "second"
strings[2] = "third"
strings[3] = "fourth"
strings[4] = "fifth"
```

가변인자는 동적으로 사용하기 위해(컴파일러에게 구별되기 위해), 항상 매개변수의 마지막에 선언되어야 한다고 생각합니다.

참고링크
https://stackoverflow.com/questions/66191000/why-is-the-order-of-parameters-considered-part-of-a-methods-signature-in-contex
https://stackoverflow.com/questions/44065062/order-of-arguments-while-using-string
