### ISSUE TITLE
[2장] nextInt(), nextFloat() 등의 메서드들로 연속적인 값 받기

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#2]
p.40
Scanner 클래스에는 nextInt(), nextFloat()와 같은 메서드들이 존재합니다. 
해당 메서드들은 문자열을 받아 숫자로 변환하는 수고를 덜 수 있지만 
연속적으로 값을 입력받아서 사용하기에는 까다롭다고 합니다. 

왜 이러한 메서드들이 연속적으로 값을 입력 받을 때 적합하지 않는지 궁금합니다.

**Comment by yujeongkimm** [comment]
스캐너는 기본적으로 공백을 구분문자로 사용하여 입력값을 토큰으로 나눕니다. 결과 토큰들은 다양한 메서드를 사용하여 해당 유형의 값들로 변환합니다.

nextInt()를 예로 들어보겠습니다.

**Comment by yujeongkimm** [comment]
스캐너는 기본적으로 공백을 구분문자로 사용하여 입력값을 토큰으로 나눕니다. 결과 토큰들은 다양한 메서드를 사용하여 해당 유형의 값들로 변환합니다.

_"A Scanner breaks its input into tokens using a delimiter pattern, which by default matches whitespace. The resulting tokens may then be converted into values of different types using the various next methods."_
from. Docs.Oracle

nextInt()를 예로 들어보겠습니다.

import java.util.Scanner;
public class Test{

     public static void main(String []args){
        Scanner input = new Scanner(System.in);
        int num;
        num = input.nextInt();
        System.out.println("num: " + num);
     }
}

입력 값으로 **2 3**을 주었을 때의 출력값은 num: 2 입니다.
이처럼 nextInt()는 공백문자를 구분으로 입력 받아 3은 처리되지 않은 것을 알 수 있습니다.
