### ISSUE TITLE
[7장] super와 super()

### ISSUE THREAD

**Issue by allzeroyou** [yujeongkimm/ReadingRecord#20]
p330
상속받은 멤버와 자신의 멤버와 이름이 같을 때 super을 붙여서 구별할 수 있습니다.
이때 super()은 조상 클래스의 생성자를 호출하는데 사용된다고 합니다. 

1. super와 super()의 차이점을 간단하게 설명하면 뭘까요?

이와 같은 조상 클래스 호출은 모든 클래스의 최고 조상인 Object 클래스의 생성자인 Object()까지 가서야 끝이 납니다.
그래서 Object 클래스를 제외한 모든 클래스의 생성자는 첫줄에 반드시 자신의 다른 생성자 또는 조상의 생성자를 호출해야 된다고 합니다. 그렇지 않으면 컴파일러는 생성자의 첫 줄에 super(); 을 자동으로 추가합니다.

2. 컴파일러가 알아서 부모 생성자를 호출해주는 메소드 super()를 추가해주는데(컴파일러 자동호출이니까 생략 가능), 그럼 super() 메소드를 언제 쓰는 건지 궁금합니다.

**Comment by Park-EunBi** [comment]
<html>
<body>
<h2>1번</h2>
<blockquote>
<p>super와 super()의 차이</p>
</blockquote>


super | super()
-- | --
참조 변수 | 생성자


<pre><code class="language-java">public class Superclass {
    int x;
    public Superclass(int x) {
        this.x = x;
    }
}

public class Subclass extends Superclass {
    int x;
    public Subclass(int x1, int x2) {
        super(x1); // calls the Superclass constructor with parameter x1
        this.x = x2;
    }
    public void printX() {
        System.out.println(&quot;x in Subclass: &quot; + this.x);
        System.out.println(&quot;x in Superclass: &quot; + super.x);
    }
}
</code></pre>
<hr>
<h3><code>super</code></h3>
<p>자손 클래스에서 조상 클래스로 부터 상속 받은 멤버를 참조하는데 사용되는 참조변수</p>
<p>상속 받은 멤버와 자신의 멤버의 이름이 같을 때 <code>super</code>를 붙여 구분</p>
<p>조상 클래스로부터 상속받은 멤버도 자손 클래스 자신의 멤버이기에 <code>this</code>를 사용할 수 있다. 그래도 조상 클래스의 멤버와 자손 클래스이 멤버가 중복 정의되어 서로 구별해야 하는 경우에만 <code>super</code>를 사용하는 것이 좋다</p>
<p><code>this</code>와 유사한 기능 - 조상의 멤버와 자신의 멤버를 구분하는데 사용된다는 점을 제외하고 근본적으로 같다</p>
<pre><code class="language-java">class Parent {
	int x = 10;
}

class Child extends Parent {
	int x = 20;
	
	void methid() {
		System.out.println(&quot;x = &quot; + x); // 20 - 자신의 멤버 변수 
		System.out.println(&quot;this.x = &quot; + this.x); // 20 - 자신의 멤버 변수 
		System.out.println(&quot;super.x = &quot; + super.x); // 10 - 조상의 멤버 변수 (이름이 같음)
}
</code></pre>
<pre><code class="language-java">// 메서드에서도 사용 가능 

class Point {
	String getLocation() {
		return &quot;x: &quot; + x + &quot;, t : &quot; + y;
}

class Point3D extends Point {
	String getLocation() {
		return super.getLocation() + &quot;, z : &quot; + z; // 조상 메서드 호출
		}
}
</code></pre>
<p>조상 클래스의 메서드에 추가적인 내용을 덧붙이고 싶다면 <code>super</code>를 사용하는 것이 좋다</p>
<p>이후에 조상 클래스의 메서드가 변경되더라도 변경된 내용이 자손 클래스에 자동적으로 반영되기 때문</p>
<h3><code>super()</code></h3>
<p>자손 클래스에서 조상 클래스의 생성자를 불러 초기화 할 때 사용</p>
<pre><code class="language-java">public class Superclass {
    int x;

    public Superclass(int x) {
        this.x = x;
    }
}

public class Subclass extends Superclass {
    int y;

    public Subclass(int x, int y) {
        super(x); // calls the Superclass constructor with parameter x
        this.y = y;
    }
}
</code></pre>
<h2>2번</h2>
<blockquote>
<p>super()을 사용해야 하는 경우</p>
</blockquote>
<p>컴파일러는 다른 파라미터가 필요하지 않는 기본 생성자만을 생성한다</p>
<p>그러므로 조상 클래스에서 기본 생성자가 아닌 파라미터를 받아야 하는 생성자를 사용해야 한다면 super()를 사용하여 반드시 적절한 생성자를 불러와야 한다</p>
<pre><code class="language-java">public class Animal {
  private String name;
  
  public Animal(String name) {
    this.name = name;
  }
}

public class Dog extends Animal {
  private String breed;
  
  public Dog(String name, String breed) {
    super(name); // Call the constructor of the Animal class
    this.breed = breed;
  }
}
</code></pre>

</body>
</html>
