### ISSUE TITLE
[2장] 부호 비트를 사용하는 경우와 2의 보수를 사용하는 경우 

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#3]
p. 50~
2진수로 음수를 표현하는 방법에는 
부호 비트를 사용하는 방법과 2의 보수를 사용하는 방법이 있다고 학습하였습니다. 
또한, 현재 대부분의 시스템이 2의 보수 방법으로 부호가 있는 정수를 표현한다고 합니다.

그렇다면 부호 비트를 사용하여 이진수의 부호를 나타내는 방법은 언제 사용하는 것인지 궁금합니다. 
> 후반부에 해결된 질문

**Comment by yujeongkimm** [comment]
컴퓨터에서 음수를 표현하는 방법에는 **부호비트방식, 1의 보수, 2의 보수**로 크게 3가지가 있습니다.

부호비트 방식은 0과 양수, 음수를 표현할 수 있는 가장 단순한 방법으로 **최상위 비트로 부호를 표현**하고, 나머지 비트로 해당 정수의 절댓값을 나타냅니다. 최상위 비트가 0이면 양수라는 뜻이고, 1이면 음수라는 뜻입니다. 

하지만 이 방식은 문제점을 가지고 있습니다. 첫 번째로 0을 나타내는 방식이 2 개라는 점입니다. 
즉 0000 도 0(+0)이고, 1000 도 0(-0) 입니다.
0을 표현하는 방법이 두 가지라면, 어떠한 데이터가 0인지 확인하기 위해 쓸데없이 컴퓨터 자원을 낭비하게 됩니다.

또 다른 문제로는, 양수와 음수의 덧셈을 수행할 때 부호를 고려해서 수행해야 한다는 점입니다.
예를 들어 0001과 0101을 더하면 0110 이 됩니다.
0001과 1001을 더할 때는 1001이 사실은 -1이므로 뺄셈을 수행해야 합니다.
따라서 덧셈 알고리즘이 좀 더 복잡해집니다.

double이나 float처럼 소수인 데이터를 다루는 방식(부동 소수점 표현)에는 부호비트를 도입하여 음수인지 양수인지를 표현하고 있습니다. 실제로 부동 소수점 표현법에는 -0과 +0이 있습니다.
하지만 정수를 표현하는 방식에서는 부호 비트를 사용하는 방식은 문제점이 있습니다.
