### ISSUE TITLE
[3장] 문자열 비교 

### ISSUE THREAD

**Issue by Park-EunBi** [yujeongkimm/ReadingRecord#4]
p.112 
두 문자열을 비교할 때에는 비교 연산자 '==' 대신 equals()라는 메소드를 사용해야 한다고 합니다. 
비교 연산자는 두 문자열이 완전히 같은 지를 비교하는 것이기에 문자열의 내용을 비교하는 데에는 사용할 수 없다고 하는데 

두 문자열이 완전히 같은지 비교하는 것과 
문자열의 내용이 동일한지 확인하는 것의 차이가 무엇인지 궁금합니다. 

> 후반부에 해결된 질문

**Comment by oownoey** [comment]
p.112 하단의 내용과 같이 String은 클래스이므로, new를 사용하여 아래와 같이 객체를 생성해야 합니다.
**String str1 = new String("abc");** 
이는 **String str2 = "abc";** 와 같이 간단한 문장으로도 표현이 가능한데, 이 방식을 문자열 리터럴(String literal) 이라고 합니다. 이 둘은 생성되는 문자열이 같지만 내부적으로 저장되는 위치가 다릅니다.

리터럴을 사용해 생성된 문자열은 Heap 내부에 존재하는 Constant String Pool에 저장됩니다. 
또한 new 연산자를 사용해 생성된 문자열은 Heap 내부에 저장됩니다.
위에서 예시로 든 str1과 str2는 "abc"라는 공통된 값을 가지고 있지만, 
다른 위치에 있는 문자열 객체의 값을 저장하게 됩니다.

== 연산자와 equals() 메소드의 가장 큰 차이점은 
== 연산자는 비교하고자 하는 두개의 대상의 주소값을 비교하는데 반해, 
equals() 메소드는 비교하고자 하는 두개의 대상의 값 자체를 비교한다는 것입니다. 

따라서 문자열을 비교하기 위해서는 
해당 문자열의 주소를 비교하는 == 연산자가 아닌
문자 하나하나를 비교하여 값이 같으면 True를 반환하는 equals() 메소드를 사용해야 합니다.
