### ISSUE TITLE
[4장] switch문의 제약조건과 if문을 사용해야하는 경우

### ISSUE THREAD

**Issue by yujeongkimm** [yujeongkimm/ReadingRecord#8]
p.146
swtich문은 단 하나의 조건식으로 많은 경우의 수를 처리할 수 있고, 표현이 간결하여 알아보기 쉽습니다.
다만 switch문은 제약조건이 있기 때문에, 경우의 수가 많아도 어쩔 수 없이 if문으로 작성해야 하는 경우가 있다고 합니다. 

1. switch문의 제약조건이 궁금합니다.
2. 이 제약조건으로 인해 if문으로 작성을 해야하는 경우가 궁금합니다. 

> 후반부에 해결된 질문

**Comment by Park-EunBi** [comment]
1. switch 문의 제약 조건은 다음과 같습니다.
- switch문의 조건식의 결과는 정수 또는 문자열이어야 한다. 
- case 문의 값은 정수 상수만 가능하며, 중복되지 않아야 한다.

switch문을 작성할 때에는 위의 두 조건을 반드시 지켜야 하며, 지키지 않을시에는 error가 발생하게 됩니다. 

2. 이러한 제약 조건으로 모든 if문을 switch 문으로 변경할 수 업습니다. 
if문을 switch문으로 변경할 수 없는 경우는 다음과 같습니다. 
- if문의 조건식에서 부등식이 사용되는 경우
- 조건식의 결과가 실수가 되는 경우 
- 등등 

예를 들어 
- 각 학생들의 성적의 평균 값으로 등급을 결정해야 한다면
   if문에서 바로 switch문으로 변경할 수 없으며 
  해당 값을 정수로 변경하는 등의 추가적인 작업이 필요합니다. 

```java
    int score = 85;
    int grade = score/10;

    switch(grade) {
        case 10:
            System.out.println("등급 A");
        break;

        case 9:
            System.out.println("등급 B");
        break;

        case 8:
            System.out.println("등급 C");
        break;

        default:
            System.out.println("등급 F"); 
    }
```
