### ISSUE TITLE
[5장] System.out.println()가 char배열을 다루는 원리

### ISSUE THREAD

**Issue by yujeongkimm** [yujeongkimm/ReadingRecord#9]
p.191
System.out.prinln()의 매개변수로 배열을 가리키는 변수를 출력하면 '타입@주소' 형식으로 출력되어 별로 얻을 정보가 없다고 합니다. 
하지만 예외적으로 char배열을 println메서드로 출력하면 각 요소가 구분자없이 그대로 출력된다고 합니다.

```java
int[] iArr = { 100, 95, 80, 70, 60 };
System.out.println(iArr);    //[I@14318bb와 같은 형식의 문자열이 출력된다.

char[] chArr = {'a', 'b', 'c', 'd' };
System.out.println(chArr);    //abcd가 출력된다.
```

System.out.println() 함수가 char 배열을 매개변수로 받을 때의 처리 과정(함수의 내부 원리)이 궁급합니다.

**Comment by allzeroyou** [comment]
좋은 질문 감사합니다.
평소에 매우 궁금했지만, 그냥 지나쳤던 내용이었는데, 이렇게 이슈 달아주셔서 덕분에 오랜만에 지적호기심 채웠습니다!

--------------
우선, 
System.out.println() 의 처리 과정부터 알아야 합니다.

System 클래스: java.lang 패키지에 속하는 클래스이기 때문에 import 하지 않고 사용 가능함.
System.out: System 클래스안의 static 변수이고, PrintStream의 객체 out 변수.
static 변수이기에 인스턴스 생성을 따로 하지않아도 System.out으로 바로 접근 가능.

이때 PrintSteam 은 println(char[])을 오버로드한 메소드를 가지는 클래스입니다. 
따라서 println(char[])는 char 배열의 문자들을 넣으면 예쁘게 출력할 수 있습니다.

이때, println(char[])은 다른 자료형 배열을 오버로드 하지 않기 때문에, int[] 배열은 println(char[]) 가 아닌 println(Object)라는 메소드로 처리됩니다. 이 메소드는 Object를 문자열로 전환합니다.(toString() 메소드에 의해서요)

toString() 메소드는 모든 배열의 default인 Object 클래스를 상속하고 있으며, 객체가 가지는 정보나 값들(their class name and default hashcode)을 리턴합니다. 말씀하신 우리한테 별로 얻을 정보가 없는 것들도요.

따라서 char형 이 아닌 int형 배열을 출력하면 '타입@주소' 형식이 출력되는 이유이며, 바르게 int형을 출력하려면 Array.toString(int[])을 사용해야 하는 이유입니다.

결국, 이러한 원리에 의해서 char배열을 매개변수로 받으면 배열의 문자들을 그대로 출력할 수 있다고 저는 이해했습니다. 
자바를 공부한지 얼마 안되었으니, 틀린 부분 있다면 알려주세요!


참고
https://stackoverflow.com/questions/24832191/difference-between-printing-char-and-int-arrays-in-java
https://sangwoo0727.github.io/java/JAVA-sysout/
https://selfdevelope.tistory.com/560
